[project]
name = "python"
version = "0.1.0"
description = "Python scraper for holland2stay"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.0",
    "notebook>=7.4.7",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "selenium>=4.35.0",
]
